export function getDomRefs() {
  return {
    statusEl: document.getElementById("status") as HTMLElement,
    presetPathEl: document.getElementById("preset-path") as HTMLElement,
    appVersionEl: document.getElementById("app-version") as HTMLElement,
    toastRoot: document.getElementById("toast-root") as HTMLElement,
    gridEl: document.getElementById("grid") as HTMLElement,
    commandsEl: document.getElementById("commands") as HTMLElement,
    topServiceSlotEl: document.getElementById("top-service-slot") as HTMLElement,
    shellEl: document.querySelector(".shell") as HTMLElement | null,
    noSelectionEl: document.getElementById("no-selection") as HTMLElement,
    editorFieldsEl: document.getElementById("editor-fields") as HTMLElement,
    serviceEditorEl: document.getElementById("service-editor") as HTMLElement,
    gridColsEl: document.getElementById("grid-cols") as HTMLInputElement,
    gridRowsEl: document.getElementById("grid-rows") as HTMLInputElement,
    btnSizeWEl: document.getElementById("btn-size-w") as HTMLInputElement,
    btnSizeHEl: document.getElementById("btn-size-h") as HTMLInputElement,
    onErrorEl: document.getElementById("on-error") as HTMLInputElement,
    alwaysOnTopEl: document.getElementById("always-on-top") as HTMLInputElement,
    clickThroughBackgroundEl: document.getElementById(
      "click-through-background"
    ) as HTMLInputElement,
    showServiceInGridEl: document.getElementById("show-service-in-grid") as HTMLInputElement,
    gridBgColorEl: document.getElementById("grid-bg-color") as HTMLInputElement,
    gridBgOpacityEl: document.getElementById("grid-bg-opacity") as HTMLInputElement,
    gridBgOpacityValueEl: document.getElementById("grid-bg-opacity-value") as HTMLElement,
    btnLabelEl: document.getElementById("btn-label") as HTMLInputElement,
    btnBgEl: document.getElementById("btn-bg") as HTMLInputElement,
    btnFgEl: document.getElementById("btn-fg") as HTMLInputElement,
    btnFontEl: document.getElementById("btn-font") as HTMLInputElement,
    btnWrapEl: document.getElementById("btn-wrap") as HTMLElement,
    btnRadiusEl: document.getElementById("btn-radius") as HTMLInputElement,
    btnIconPickEl: document.getElementById("btn-icon-pick") as HTMLElement,
    btnIconClearEl: document.getElementById("btn-icon-clear") as HTMLButtonElement,
    btnIconDarkenEl: document.getElementById("btn-icon-darken") as HTMLInputElement,
    btnLabelVisibilityEl: document.getElementById("btn-label-visibility") as HTMLInputElement,
    btnPreviewEl: document.getElementById("btn-preview") as HTMLElement,
    serviceRadiusEl: document.getElementById("service-radius") as HTMLInputElement,
    tabButtonSettingsEl: document.getElementById("tab-button-settings") as HTMLElement,
    tabGridSettingsEl: document.getElementById("tab-grid-settings") as HTMLElement,
    tabConnectionsSettingsEl: document.getElementById("tab-connections-settings") as HTMLElement,
    panelButtonSettingsEl: document.getElementById("panel-button-settings") as HTMLElement,
    panelGridSettingsEl: document.getElementById("panel-grid-settings") as HTMLElement,
    panelConnectionsSettingsEl: document.getElementById(
      "panel-connections-settings"
    ) as HTMLElement,
    contactNameEl: document.getElementById("contact-name") as HTMLInputElement,
    contactProtocolEl: document.getElementById("contact-protocol") as HTMLInputElement,
    contactHostEl: document.getElementById("contact-host") as HTMLInputElement,
    contactPortEl: document.getElementById("contact-port") as HTMLInputElement,
    contactNewEl: document.getElementById("contact-new") as HTMLButtonElement,
    contactSaveEl: document.getElementById("contact-save") as HTMLButtonElement,
    contactsListEl: document.getElementById("contacts-list") as HTMLElement
  };
}
